### ISSUE TITLE
ecommerce demo won't run

### ISSUE THREAD

**Issue by edwardotis** [kmmbvnr/viewflow-demo#5]
I fixed some old requirements.txt issues:

#git+http://github.com/kmmbvnr/django-viewflow.git
django-viewflow==0.9.0
#https://bitbucket.org/mjs7231/django-dbbackup/get/master.zip
django-dbbackup==2.3.2

But still the demo won't start:

(virflowdemo)myself@my-vm:~/dev/viewflow-demo/ecommerce$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/myself/Envs/virflowdemo/lib/python3.4/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/myself/Envs/virflowdemo/lib/python3.4/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/myself/Envs/virflowdemo/lib/python3.4/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/myself/Envs/virflowdemo/lib/python3.4/site-packages/django/core/management/base.py", line 280, in execute
    translation.activate('en-us')
  File "/home/myself/Envs/virflowdemo/lib/python3.4/site-packages/django/utils/translation/__init__.py", line 130, in activate
    return _trans.activate(language)
  File "/home/myself/Envs/virflowdemo/lib/python3.4/site-packages/django/utils/translation/trans_real.py", line 188, in activate
    _active.value = translation(language)
  File "/home/myself/Envs/virflowdemo/lib/python3.4/site-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/home/myself/Envs/virflowdemo/lib/python3.4/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/home/myself/Envs/virflowdemo/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'viewflow.site'

**Comment by kmmbvnr** [comment]
yep, it a bit outdated
